/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-west-2', // change to your region
    aws_cognito_identity_pool_id: 'us-west-2:fcda6eff-e0c4-4728-a15a-1d49ac51dd32', // replace with your Identity Pool ID
    aws_user_files_s3_bucket: 'audio-bucket69', // replace with your S3 bucket name
    aws_user_files_s3_bucket_region: 'us-west-2', // change to your S3 bucket's region
};

export default awsmobile;



